[language_server.haskell]
filetypes = ["haskell"]
roots = []
command =  "/home/migsej/.local/share/nvim/mason/bin/haskell-language-server-wrapper"
args = ["--lsp"]

[language_server.uiua]
filetypes = ["ua", "uiua"]
roots = []
command =  "uiua"
args = ["lsp"]

[language_server.rust]
filetypes = ["rust"]
roots = []
command =  "rust-analyzer"

[language_server.latex]
filetypes = ["latex", "tex"]
roots = []
command =  "texlab"
args = []

